# Points to the HFC config file
ontologyFile:       src/main/resources/ontology/chatcat.yml

# ########## COMPILE CONFIGURATION SETTINGS ##########
inputFile:          src/main/rudi/ChatCat.rudi
outputDirectory:    src/main/gen-java
agentBase:          de.dfki.chatcat.ChatAgent
typeDef:            ChatAgent.rudi
failOnError:        false
rootPackage:        de.dfki.chatcat
nameToURI:
  Agent: <cat:Agent>
nameToClass:
  Date: de.dfki.chatcat.util.Date
#printErrors: true      # TODO: DESCRIBE
#visualise: true        # produces a graphical representation of the parsed rule files
                        # with type resolution information
#persistentVars: true   # puts compiler into persistent variables mode: local variables
                        # in included rule files also keep their values during runtime


# ########## RUN CONFIGURATION SETTINGS ##########
NLG:
  eng:
    class: de.dfki.mlt.rudimant.agent.nlp.LanguageGenerator
    mapperProject: src/main/resources/grammars/cplanner/allrules-mapper
    generationProject: src/main/resources/grammars/cplanner/allrules
    #translateNumbers: true  # translates numbers to text internally, if, e.g., the TTS
                             # can not do it by itself
NLU:
  eng:
    class: de.dfki.mlt.rudimant.agent.nlp.SrgsParser
    grammar: src/main/resources/grammars/srgs/chatcat.abnf
    converter: src/main/resources/grammars/cplanner/srgsconv
    tokenizer:
      class: de.dfki.mlt.rudimant.agent.nlp.TrivialTokenizer
      toLower: false           # turn all output to lower case
      removePunctuation: true  # remove all punctuation tokens

# ########## DEBUGGER/GUI SETTINGS ##########
debugPort: 9777

customCompileCommands:
  mvncompile: mvn install
  mvncleancmp: mvn clean install
  vcompile: vondac -v -c config.yml
defaultCompileCommand: Compile
